### ISSUE TITLE
Errors for some D-Space Repositories

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/DspaceConnector#10]
I was testing various repos from http://registry.duraspace.org/ 

This one works: http://drum.lib.umd.edu/  (http://registry.duraspace.org/registry/repository/2627) 

but if I put these in DSpace URL and hit "get collections" I get a "something went wrong" error message:
- https://dspace.allegheny.edu/ ( http://registry.duraspace.org/registry/repository/1368 )
- http://bir.brandeis.edu/ ( http://registry.duraspace.org/registry/repository/1477 )
- https://digitalarchive.wm.edu/ ( http://registry.duraspace.org/registry/repository/1548 )

Are there parameters for what does and doesn't work (DSpace version?)

**Comment by patrickmj** [comment]
Yes, it's only designed for version 4 or above. There's not a good way to test the version, but I can add that suggestion to the error message.

**Comment by mebrett** [comment]
The good news is that the registry lists DSpace version - best bet is probably to put the minimum version for the module in the documentation as well as in the error message.

**Comment by patrickmj** [comment]
fixed in aea480e89eacbb8f29918215f8c13f4cd3bd74f6
