### ISSUE TITLE
Run through importing

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/DspaceConnector#19]
From a couple sites here  http://registry.duraspace.org/registry/dspace using version 4 or greater, run through importing a collection and a community.

This is just to check if there were any regressions from the core updates.

Develop branch of the module

**Comment by mebrett** [comment]
I've tried the URL of three DSpace repositories and I can't get the module to load collections or comminuties. 

Log reads: 

```

2016-03-01T17:10:04+00:00 ERR (3): exception 'RuntimeException' with message 'Requested "http://mars.gmu.edu//rest/collections" got "HTTP/1.1 500 Internal Server Error".' in /websites/omekadev/home/www/mebrett/testomekas/modules/DspaceConnector/src/Controller/IndexController.php:53
Stack trace:
#0 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): DspaceConnector\Controller\IndexController->fetchAction()
#1 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#2 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#3 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#4 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#6 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /websites/omekadev/home/www/mebrett/testomekas/index.php(17): Zend\Mvc\Application->run()
#11 {main}
```

**Comment by patrickmj** [comment]
Thanks. Could you give the urls of the DSpace repos you tested? It looks like a new odd thing on my side, but having the different repos will help.

**Comment by mebrett** [comment]
http://archives.lib.state.ma.us/, https://digitalarchive.wm.edu/, and http://mars.gmu.edu/

**Comment by patrickmj** [comment]
Oddly, I'm getting a failure, but nothing logged. The error message looks like it comes from mars. Does the same/similar message come from the other two sites?

**Comment by mebrett** [comment]
`2016-03-01T18:21:21+00:00 ERR (3): exception 'RuntimeException' with message 'Requested "http://archives.lib.state.ma.us//rest/collections" got "HTTP/1.1 404 Not Found".' in /websites/omekadev/home/www/mebrett/testomekas/modules/DspaceConnector/src/Controller/IndexController.php:53`

and

`2016-03-01T18:22:01+00:00 ERR (3): exception 'ErrorException' with message 'stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:281`

**Comment by mebrett** [comment]
The second is for William and Mary, which is for some reason an http**s** not http uri.

**Comment by patrickmj** [comment]
Many thanks! That's three completely different exceptions for the three sites, so lots to look into. :no_good: :no_good: :no_good:

**Comment by patrickmj** [comment]
There's a _tiny_ possibility that the latest from today (develop on DspaceConnector) might help with the MA stuff. It's not working on my end, but until I figure out why errors aren't being logged on my machine, could you check that endpoint to see if the same error happens?
