### ISSUE TITLE
Connector not working with DSpace6

### ISSUE THREAD

**Issue by artturimatias** [omeka-s-modules/DspaceConnector#31]
There seems to be some issues with DSpace 6:
- only one item is imported
However, it makes requests for all items, but only one gets its way into items. 

- "remote_id" should be "uuid" instead of "id"
DSpace6 now uses UUIds instead of id. Also the type for "remote_id" in dspace_item table is int(11) so remote_ids get truncated. I tried with char(43) and it seemed to work.

- bitstreams fetch does not work
There seems to be extra "/rest"in bitsream fetch (in function processItemBitstreams). Therefore bitstream fetch does not work. By removing that hardcoded "rest" made it work again.

Maybe there should be option to set DSpace rest address? It might not be /rest always.

**Comment by patrickmj** [comment]
Thanks for the feedback! Changes in the DSpace API have been tricky to keep up with.

Do you have a public endpoint that we could use to test against?

**Comment by artturimatias** [comment]
Sorry, we are just migrating to DSpace 6 so we don't have public API yet. But there is a http://demo.dspace.org/rest/ where one can test.

**Comment by patrickmj** [comment]
Is there anything in the jobs' logs? Click "Jobs" in the left sidebar, and look for ones with class `DspaceConnector\Job\Import`. Hopefully there will be a link to logs for the job with helpful info. Most likely something starting with `PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'remote_id' cannot be null in /var/www/html/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91`, which would make perfect sense with the UUID change.

**Comment by patrickmj** [comment]
Also, what version of Omeka S core are you using?
