### ISSUE TITLE
Strict Standards error

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/DspaceConnector#39]
When deactivated and uninstalled, I still get the following error at the top of every screen when I have DspaceConnector downloaded:

```
Strict Standards: Declaration of DspaceConnector\Module::upgrade() should be compatible with Omeka\Module\AbstractModule::upgrade($oldVersion, $newVersion, Zend\ServiceManager\ServiceLocatorInterface $serviceLocator) in /Users/kim/Sites/omeka-s/modules/DspaceConnector/Module.php on line 75
```

I'm running PHP 5.6.30, and I've pulled the most recent updates to Omeka S and DspaceConnector.

**Comment by patrickmj** [comment]
@kimisgold rats. had missed an errors setting when I got the new laptop, so I never saw this error. Should be fixed on latest develop
