### ISSUE TITLE
'DSpace Collection Link' URL value doesn't wrap properly/spills over to other columns

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/DspaceConnector#65]
From `dspace-connector/past-imports` screen:

<img width="1026" alt="Screen Shot 2020-08-19 at 10 41 01 AM" src="https://user-images.githubusercontent.com/69479529/93378201-f44be080-f810-11ea-9872-96a34ca13217.png">

**Comment by sharonmleon** [comment]
@kimisgold Can we get some styling help here?

**Comment by sharonmleon** [comment]
Convert URL to "Link" to contain the text.

**Comment by matthewjmckinley** [comment]
Resolved by https://github.com/omeka-s-modules/DspaceConnector/commit/ad70b79983788f8871d20dc404866f441a3ceeca
