### ISSUE TITLE
Test assigning Item Set(s) and Site(s) to collection items on import

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/DspaceConnector#75]
For both the item sets and sites chosen select box on the DSpace Connector import form, please verify:

- Sites select box is pre-populated with all sites that have 'Auto Assign New Items' checked in Site Admin Settings
- Choosing multiple sets/sites and importing new collection results in sets/sites assigned within collection item's metadata
- Choosing different sites/sets and importing to update (i.e. previously imported) collection results in new sets/sites assigned within item metadata, and does not remove previously assigned sets/sites

I've been using Harvard's DSpace instance to test https://dash.harvard.edu, but feel free to test with another instance. Thanks!

**Comment by katknow** [comment]
I'm having an issue with this one as well. Been messing with it for a while now, and I keep getting this over and over (with the item that failed to copy different each time:

021-12-03T21:46:48+00:00 ERR (3): Omeka\File\Exception\RuntimeException: Failed to copy "/tmp/omeka2f4Zlg" to "/var/www/html/katknow/OmekaSTesting/files/original/b00fb579f1f8260a781b083de96610803a845164.pdf". in /var/www/html/katknow/OmekaSTesting/application/src/File/Store/Local.php:49
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/application/src/File/TempFile.php(227): Omeka\File\Store\Local->put('/tmp/omeka2f4Zl...', 'original/b00fb5...')
#1 /var/www/html/katknow/OmekaSTesting/application/src/File/TempFile.php(238): Omeka\File\TempFile->store('original')
#2 /var/www/html/katknow/OmekaSTesting/application/src/File/TempFile.php(435): Omeka\File\TempFile->storeOriginal()
#3 /var/www/html/katknow/OmekaSTesting/application/src/Media/Ingester/Url.php(72): Omeka\File\TempFile->mediaIngestFile(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore), true, true, true, true)
#4 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/MediaAdapter.php(164): Omeka\Media\Ingester\Url->ingest(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore))
#5 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/AbstractEntityAdapter.php(607): Omeka\Api\Adapter\MediaAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#6 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/ItemAdapter.php(240): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#7 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/AbstractEntityAdapter.php(607): Omeka\Api\Adapter\ItemAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#8 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/AbstractEntityAdapter.php(318): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#9 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#10 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#11 /var/www/html/katknow/OmekaSTesting/application/src/Api/Adapter/AbstractEntityAdapter.php(367): Omeka\Api\Manager->create('items', Array, Array, Array)
#12 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(227): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#13 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(97): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#14 /var/www/html/katknow/OmekaSTesting/modules/DspaceConnector/src/Job/Import.php(357): Omeka\Api\Manager->batchCreate('items', Array, Array, Array)
#15 /var/www/html/katknow/OmekaSTesting/modules/DspaceConnector/src/Job/Import.php(122): DspaceConnector\Job\Import->createItems(Array)
#16 /var/www/html/katknow/OmekaSTesting/modules/DspaceConnector/src/Job/Import.php(62): DspaceConnector\Job\Import->importCollection('/rest/collectio...')
#17 /var/www/html/katknow/OmekaSTesting/application/src/Job/DispatchStrategy/Synchronous.php(34): DspaceConnector\Job\Import->perform()
#18 /var/www/html/katknow/OmekaSTesting/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#19 /var/www/html/katknow/OmekaSTesting/application/data/scripts/perform-job.php(66): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#20 {main}

Apologies, I'm thinking it must be my OmekaS instance.

**Comment by matthewjmckinley** [comment]
This one looks like it may be a directory permissions issue--can you post the output of `ls -l /var/www/html/katknow/OmekaSTesting/files` ?

**Comment by katknow** [comment]
This is what I'm getting:

total 2040
drwxr-xr-x 2 apache  apache     110 Nov 15 12:07 asset
-rw-rw-r-- 1 katknow katknow     79 Jun  4 13:37 index.html
drwxr-xr-x 2 apache  apache  430080 Dec  3 18:55 large
drwxr-xr-x 2 apache  apache  430080 Dec  3 18:55 medium
drwxr-xr-x 2 apache  apache  434176 Dec  3 18:55 original
drwxr-xr-x 2 apache  apache  430080 Dec  3 18:55 square

**Comment by matthewjmckinley** [comment]
Since this is a testing instance, can you try fully opening all those directories up and see if you still get the same error? `chmod -R 777 files` from your `OmekaSTesting` directory. You may have to put `sudo` in front and type your password as well.

**Comment by katknow** [comment]
I definitely think there is a problem with my instance--I unchecked the box like the Fedora, and it was able to do everything as described above!

**Comment by matthewjmckinley** [comment]
OK, sounds like a separate issue. I'll close since it seems like this item set/site feature has tested successfully!
