### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/DspaceConnector#79]
Update documentation to reflect new features from latest release:

- Added ability to re-run previous jobs from past imports screen
- Added link to advanced search results for imported items on past import screen
- Changed Dspace collection link text to collection name, if found
- Added ability to test import based off limit value

**Comment by katknow** [comment]
[A draft of updates can be found here](https://github.com/omeka/omeka-s-enduser/blob/connectors-update/docs/modules/dspaceconnector.md)
