### ISSUE TITLE
Give DspaceConnector an initial run-through

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/DspaceConnector#8]
DspaceConnector could get some more eyes on it. 

Should be able to just clone this repo into the `modules` directory. Then install from the `Modules` page. 

Mars http://mars.gmu.edu should work as a good Dspace site URL to play around with. 
- Does the switch for importing files work?
- Does the info under `Past Imports` look right, and helpful?
- Does undoing work?
- Other UI, UX, expectations things to think about?

**Comment by mebrett** [comment]
Didn't work on a local install (never got beyond starting the job) but ran very smoothly on an install on dev.omeka

**Comment by patrickmj** [comment]
thanks ... it's possible that's a result of some changes since yesterday to both omeka s core and the module that I put in today, but something still smells fishy. It's sometimes hard to dig up errors that happen in jobs.

**Comment by zerocrates** [comment]
The most common problems at the "starting" stage for jobs are us just not being able to "guess" the PHP path (or the PHP CLI simply not being installed, but that's fairly unlikely here since you need it to run Composer)

**Comment by mebrett** [comment]
I can try it again if you like - I was using the zip of core in both cases, but in one the latest instance of the connector on dev (this morning, vs. yesterday with the local)

**Comment by patrickmj** [comment]
So, we'll have to back up a bit. 1) the zip doesn't reflect the changes I mentioned, so the current module is now out of sync with it. 2) the shared testing environment doesn't look like it is on PHP 5.5 yet. 3) it looks like, in the shared environment, there are changes to the ant build script, so I'm hesitant to try running it again. 

Upshot -- to test the current module, we'll have to get everything synced back up again, and do what John says of figuring out the path if it is in another environment.

**Comment by mebrett** [comment]
I will hold off any further testing until Monday in that case.

**Comment by patrickmj** [comment]
if it worked in one environment, feedback on the process from there might still be useful

**Comment by patrickmj** [comment]
Just noting -- some changes to core will call for some changes to the module. So if we keep everything in sync I'll have to update this before it should be expected to work at all.

**Comment by patrickmj** [comment]
@mebrett pushed up changes based on core changes, so can probably look at the original questions again. Thanks!

**Comment by mebrett** [comment]
And it's still stuck on "starting"

**Comment by patrickmj** [comment]
This is on the shared installation on dev?

**Comment by mebrett** [comment]
Yes. Job ID 5

**Comment by patrickmj** [comment]
Looks like we're probably stuck until https://github.com/omeka/omeka-s/issues/327 is resolved.

UI and UX thoughts on import page will still be possible and helpful even before that's resolved, if you have any.

**Comment by patrickmj** [comment]
Huzzah!!! :beers: Looks like we're in business to try this again now that the site is properly configured!

In addition to the original bullet list of things to look at, it'll be helpful to 
- try lots of different collections and communities
- check how the 'comment' part of the import might be used
- look at different imported files to see what does and does not get thumbnails (as of this post, the site is configured to use GdThumbnailer)

**Comment by mebrett** [comment]
Found more DSpace repos here: http://registry.duraspace.org/registry/dspace but about half the time I'd try to get communities/collections, the module threw an error. Are there parameters for what settings/features a DSpace repo must have to be compatible with the module?

**Comment by mebrett** [comment]
An additional thought, unrelated to any testing request - if one enters a repo url and then hits Return on the keyboard, the module seems to start running an empty job. It doesn't import anything or delete the url from the DSpace field, but it does create a job (and since we can't delete jobs from the list, this adds to visual clutter).
